### ISSUE TITLE
Invite logs have multiple Call-ID tags applied.

### ISSUE THREAD

**Issue by andgith** [davehorton/drachtio-basic-registrar#2]
During my testing I have noticed that my INVITE logs have multiple Call-ID added.

I believe these are applied here: 
`if (process.env.NODE_ENV !== 'test') logger = logger.child({'Call-ID': req.get('Call-ID')});`

Looks like this is intended behaviour for Pino:
http://getpino.io/#/docs/child-loggers?id=cost-of-child-logging

However wont the logs keep growing in size if the Call-ID is always appended?

Thanks

**Comment by davehorton** [comment]
Good find.  Will make a fix shortly
